import { IPlaybackCtx } from "./IPlayback";
import { WMF } from "./WMF";
import { SerializableRecord } from "./Serializable";
import { META_ESCAPE } from "./records/META_ESCAPE";
import { META_SETWINDOWEXT } from "./records/META_SETWINDOWEXT";
import { META_SETWINDOWORG } from "./records/META_SETWINDOWORG";
import { META_SETTEXTALIGN } from "./records/META_SETTEXTALIGN";
import { META_SETTEXTCOLOR } from "./records/META_SETTEXTCOLOR";
import { META_CREATEPENINDIRECT } from "./records/META_CREATEPENINDIRECT";
import { Pen } from "./structs/Pen";
import { LogBrush } from "./structs/LogBrush";
import { PointS } from "./structs/PointS";
import { META_SETPOLYFILLMODE } from "./records/META_SETPOLYFILLMODE";
import { META_SETMAPMODE } from "./records/META_SETMAPMODE";
import { META_SETBKMODE } from "./records/META_SETBKMODE";
import { META_SETROP2 } from "./records/META_SETROP2";
import { META_SELECTOBJECT } from "./records/META_SELECTOBJECT";
import { META_CREATEBRUSHINDIRECT } from "./records/META_CREATEBRUSHINDIRECT";
import { META_DELETEOBJECT } from "./records/META_DELETEOBJECT";
import { META_POLYGON } from "./records/META_POLYGON";
import { SETMITERLIMIT } from "./escapes/SETMITERLIMIT";
export declare function isEscape(record: SerializableRecord): record is META_ESCAPE;
export declare type WMFObject = Pen | LogBrush;
export declare abstract class BasicPlayback {
    protected wmf: WMF;
    protected ctx: IPlaybackCtx;
    private objectTable;
    private viewExt;
    private viewOrigin;
    protected abstract updateViewBox(ext: PointS, origin: PointS): void;
    protected abstract drawPolygon(points: PointS[]): void;
    constructor(wmfObject: WMF);
    protected getObject(index: number): WMFObject | null;
    protected putObject(obj: any): void;
    META_SETWINDOWEXT(record: META_SETWINDOWEXT): void;
    META_SETWINDOWORG(record: META_SETWINDOWORG): void;
    META_SETTEXTALIGN(record: META_SETTEXTALIGN): void;
    META_SETTEXTCOLOR(record: META_SETTEXTCOLOR): void;
    META_CREATEPENINDIRECT(record: META_CREATEPENINDIRECT): void;
    META_SETPOLYFILLMODE(record: META_SETPOLYFILLMODE): void;
    META_SETMAPMODE(record: META_SETMAPMODE): void;
    META_SETBKMODE(record: META_SETBKMODE): void;
    META_SETROP2(record: META_SETROP2): void;
    META_SELECTOBJECT(record: META_SELECTOBJECT): void;
    META_CREATEBRUSHINDIRECT(record: META_CREATEBRUSHINDIRECT): void;
    META_DELETEOBJECT(record: META_DELETEOBJECT): void;
    META_EOF(): void;
    META_POLYGON(record: META_POLYGON): void;
    ESCAPE_SETMITERLIMIT(escape: SETMITERLIMIT): void;
}
