"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FloodFill = exports.TextAlign = exports.HatchStyle = exports.BrushStyle = exports.PenStyle = exports.MetafileEscapes = exports.BinaryRasterOperation = exports.PolyFillMode = exports.MixMode = exports.MapMode = exports.RecordType = exports.MetafileVersion = exports.MetafileType = void 0;
var MetafileType;
(function (MetafileType) {
    MetafileType[MetafileType["MEMORYMETAFILE"] = 1] = "MEMORYMETAFILE";
    MetafileType[MetafileType["DISKMETAFILE"] = 2] = "DISKMETAFILE";
})(MetafileType = exports.MetafileType || (exports.MetafileType = {}));
;
var MetafileVersion;
(function (MetafileVersion) {
    MetafileVersion[MetafileVersion["META_VERSION100"] = 256] = "META_VERSION100";
    MetafileVersion[MetafileVersion["META_VERSION300"] = 768] = "META_VERSION300";
})(MetafileVersion = exports.MetafileVersion || (exports.MetafileVersion = {}));
;
var RecordType;
(function (RecordType) {
    RecordType[RecordType["META_EOF"] = 0] = "META_EOF";
    RecordType[RecordType["META_REALIZEPALETTE"] = 53] = "META_REALIZEPALETTE";
    RecordType[RecordType["META_SETPALENTRIES"] = 55] = "META_SETPALENTRIES";
    RecordType[RecordType["META_SETBKMODE"] = 258] = "META_SETBKMODE";
    RecordType[RecordType["META_SETMAPMODE"] = 259] = "META_SETMAPMODE";
    RecordType[RecordType["META_SETROP2"] = 260] = "META_SETROP2";
    RecordType[RecordType["META_SETRELABS"] = 261] = "META_SETRELABS";
    RecordType[RecordType["META_SETPOLYFILLMODE"] = 262] = "META_SETPOLYFILLMODE";
    RecordType[RecordType["META_SETSTRETCHBLTMODE"] = 263] = "META_SETSTRETCHBLTMODE";
    RecordType[RecordType["META_SETTEXTCHAREXTRA"] = 264] = "META_SETTEXTCHAREXTRA";
    RecordType[RecordType["META_RESTOREDC"] = 295] = "META_RESTOREDC";
    RecordType[RecordType["META_RESIZEPALETTE"] = 313] = "META_RESIZEPALETTE";
    RecordType[RecordType["META_DIBCREATEPATTERNBRUSH"] = 322] = "META_DIBCREATEPATTERNBRUSH";
    RecordType[RecordType["META_SETLAYOUT"] = 329] = "META_SETLAYOUT";
    RecordType[RecordType["META_SETBKCOLOR"] = 513] = "META_SETBKCOLOR";
    RecordType[RecordType["META_SETTEXTCOLOR"] = 521] = "META_SETTEXTCOLOR";
    RecordType[RecordType["META_OFFSETVIEWPORTORG"] = 529] = "META_OFFSETVIEWPORTORG";
    RecordType[RecordType["META_LINETO"] = 531] = "META_LINETO";
    RecordType[RecordType["META_MOVETO"] = 532] = "META_MOVETO";
    RecordType[RecordType["META_OFFSETCLIPRGN"] = 544] = "META_OFFSETCLIPRGN";
    RecordType[RecordType["META_FILLREGION"] = 552] = "META_FILLREGION";
    RecordType[RecordType["META_SETMAPPERFLAGS"] = 561] = "META_SETMAPPERFLAGS";
    RecordType[RecordType["META_SELECTPALETTE"] = 564] = "META_SELECTPALETTE";
    RecordType[RecordType["META_POLYGON"] = 804] = "META_POLYGON";
    RecordType[RecordType["META_POLYLINE"] = 805] = "META_POLYLINE";
    RecordType[RecordType["META_SETTEXTJUSTIFICATION"] = 522] = "META_SETTEXTJUSTIFICATION";
    RecordType[RecordType["META_SETWINDOWORG"] = 523] = "META_SETWINDOWORG";
    RecordType[RecordType["META_SETWINDOWEXT"] = 524] = "META_SETWINDOWEXT";
    RecordType[RecordType["META_SETVIEWPORTORG"] = 525] = "META_SETVIEWPORTORG";
    RecordType[RecordType["META_SETVIEWPORTEXT"] = 526] = "META_SETVIEWPORTEXT";
    RecordType[RecordType["META_OFFSETWINDOWORG"] = 527] = "META_OFFSETWINDOWORG";
    RecordType[RecordType["META_SCALEWINDOWEXT"] = 1040] = "META_SCALEWINDOWEXT";
    RecordType[RecordType["META_SCALEVIEWPORTEXT"] = 1042] = "META_SCALEVIEWPORTEXT";
    RecordType[RecordType["META_EXCLUDECLIPRECT"] = 1045] = "META_EXCLUDECLIPRECT";
    RecordType[RecordType["META_INTERSECTCLIPRECT"] = 1046] = "META_INTERSECTCLIPRECT";
    RecordType[RecordType["META_ELLIPSE"] = 1048] = "META_ELLIPSE";
    RecordType[RecordType["META_FLOODFILL"] = 1049] = "META_FLOODFILL";
    RecordType[RecordType["META_FRAMEREGION"] = 1065] = "META_FRAMEREGION";
    RecordType[RecordType["META_ANIMATEPALETTE"] = 1078] = "META_ANIMATEPALETTE";
    RecordType[RecordType["META_TEXTOUT"] = 1313] = "META_TEXTOUT";
    RecordType[RecordType["META_POLYPOLYGON"] = 1336] = "META_POLYPOLYGON";
    RecordType[RecordType["META_EXTFLOODFILL"] = 1352] = "META_EXTFLOODFILL";
    RecordType[RecordType["META_RECTANGLE"] = 1051] = "META_RECTANGLE";
    RecordType[RecordType["META_SETPIXEL"] = 1055] = "META_SETPIXEL";
    RecordType[RecordType["META_ROUNDRECT"] = 1564] = "META_ROUNDRECT";
    RecordType[RecordType["META_PATBLT"] = 1565] = "META_PATBLT";
    RecordType[RecordType["META_SAVEDC"] = 30] = "META_SAVEDC";
    RecordType[RecordType["META_PIE"] = 2074] = "META_PIE";
    RecordType[RecordType["META_STRETCHBLT"] = 2851] = "META_STRETCHBLT";
    RecordType[RecordType["META_ESCAPE"] = 1574] = "META_ESCAPE";
    RecordType[RecordType["META_INVERTREGION"] = 298] = "META_INVERTREGION";
    RecordType[RecordType["META_PAINTREGION"] = 299] = "META_PAINTREGION";
    RecordType[RecordType["META_SELECTCLIPREGION"] = 300] = "META_SELECTCLIPREGION";
    RecordType[RecordType["META_SELECTOBJECT"] = 301] = "META_SELECTOBJECT";
    RecordType[RecordType["META_SETTEXTALIGN"] = 302] = "META_SETTEXTALIGN";
    RecordType[RecordType["META_ARC"] = 2071] = "META_ARC";
    RecordType[RecordType["META_CHORD"] = 2096] = "META_CHORD";
    RecordType[RecordType["META_BITBLT"] = 2338] = "META_BITBLT";
    RecordType[RecordType["META_EXTTEXTOUT"] = 2610] = "META_EXTTEXTOUT";
    RecordType[RecordType["META_SETDIBTODEV"] = 3379] = "META_SETDIBTODEV";
    RecordType[RecordType["META_DIBBITBLT"] = 2368] = "META_DIBBITBLT";
    RecordType[RecordType["META_DIBSTRETCHBLT"] = 2881] = "META_DIBSTRETCHBLT";
    RecordType[RecordType["META_STRETCHDIB"] = 3907] = "META_STRETCHDIB";
    RecordType[RecordType["META_DELETEOBJECT"] = 496] = "META_DELETEOBJECT";
    RecordType[RecordType["META_CREATEPALETTE"] = 247] = "META_CREATEPALETTE";
    RecordType[RecordType["META_CREATEPATTERNBRUSH"] = 505] = "META_CREATEPATTERNBRUSH";
    RecordType[RecordType["META_CREATEPENINDIRECT"] = 762] = "META_CREATEPENINDIRECT";
    RecordType[RecordType["META_CREATEFONTINDIRECT"] = 763] = "META_CREATEFONTINDIRECT";
    RecordType[RecordType["META_CREATEBRUSHINDIRECT"] = 764] = "META_CREATEBRUSHINDIRECT";
    RecordType[RecordType["META_CREATEREGION"] = 1791] = "META_CREATEREGION";
})(RecordType = exports.RecordType || (exports.RecordType = {}));
;
var MapMode;
(function (MapMode) {
    MapMode[MapMode["MM_TEXT"] = 1] = "MM_TEXT";
    MapMode[MapMode["MM_LOMETRIC"] = 2] = "MM_LOMETRIC";
    MapMode[MapMode["MM_HIMETRIC"] = 3] = "MM_HIMETRIC";
    MapMode[MapMode["MM_LOENGLISH"] = 4] = "MM_LOENGLISH";
    MapMode[MapMode["MM_HIENGLISH"] = 5] = "MM_HIENGLISH";
    MapMode[MapMode["MM_TWIPS"] = 6] = "MM_TWIPS";
    MapMode[MapMode["MM_ISOTROPIC"] = 7] = "MM_ISOTROPIC";
    MapMode[MapMode["MM_ANISOTROPIC"] = 8] = "MM_ANISOTROPIC";
})(MapMode = exports.MapMode || (exports.MapMode = {}));
;
var MixMode;
(function (MixMode) {
    MixMode[MixMode["TRANSPARENT"] = 1] = "TRANSPARENT";
    MixMode[MixMode["OPAQUE"] = 2] = "OPAQUE";
})(MixMode = exports.MixMode || (exports.MixMode = {}));
;
var PolyFillMode;
(function (PolyFillMode) {
    PolyFillMode[PolyFillMode["ALTERNATE"] = 1] = "ALTERNATE";
    PolyFillMode[PolyFillMode["WINDING"] = 2] = "WINDING";
})(PolyFillMode = exports.PolyFillMode || (exports.PolyFillMode = {}));
;
var BinaryRasterOperation;
(function (BinaryRasterOperation) {
    BinaryRasterOperation[BinaryRasterOperation["R2_BLACK"] = 1] = "R2_BLACK";
    BinaryRasterOperation[BinaryRasterOperation["R2_NOTMERGEPEN"] = 2] = "R2_NOTMERGEPEN";
    BinaryRasterOperation[BinaryRasterOperation["R2_MASKNOTPEN"] = 3] = "R2_MASKNOTPEN";
    BinaryRasterOperation[BinaryRasterOperation["R2_NOTCOPYPEN"] = 4] = "R2_NOTCOPYPEN";
    BinaryRasterOperation[BinaryRasterOperation["R2_MASKPENNOT"] = 5] = "R2_MASKPENNOT";
    BinaryRasterOperation[BinaryRasterOperation["R2_NOT"] = 6] = "R2_NOT";
    BinaryRasterOperation[BinaryRasterOperation["R2_XORPEN"] = 7] = "R2_XORPEN";
    BinaryRasterOperation[BinaryRasterOperation["R2_NOTMASKPEN"] = 8] = "R2_NOTMASKPEN";
    BinaryRasterOperation[BinaryRasterOperation["R2_MASKPEN"] = 9] = "R2_MASKPEN";
    BinaryRasterOperation[BinaryRasterOperation["R2_NOTXORPEN"] = 10] = "R2_NOTXORPEN";
    BinaryRasterOperation[BinaryRasterOperation["R2_NOP"] = 11] = "R2_NOP";
    BinaryRasterOperation[BinaryRasterOperation["R2_MERGENOTPEN"] = 12] = "R2_MERGENOTPEN";
    BinaryRasterOperation[BinaryRasterOperation["R2_COPYPEN"] = 13] = "R2_COPYPEN";
    BinaryRasterOperation[BinaryRasterOperation["R2_MERGEPENNOT"] = 14] = "R2_MERGEPENNOT";
    BinaryRasterOperation[BinaryRasterOperation["R2_MERGEPEN"] = 15] = "R2_MERGEPEN";
    BinaryRasterOperation[BinaryRasterOperation["R2_WHITE"] = 16] = "R2_WHITE";
})(BinaryRasterOperation = exports.BinaryRasterOperation || (exports.BinaryRasterOperation = {}));
;
var MetafileEscapes;
(function (MetafileEscapes) {
    MetafileEscapes[MetafileEscapes["NEWFRAME"] = 1] = "NEWFRAME";
    MetafileEscapes[MetafileEscapes["ABORTDOC"] = 2] = "ABORTDOC";
    MetafileEscapes[MetafileEscapes["NEXTBAND"] = 3] = "NEXTBAND";
    MetafileEscapes[MetafileEscapes["SETCOLORTABLE"] = 4] = "SETCOLORTABLE";
    MetafileEscapes[MetafileEscapes["GETCOLORTABLE"] = 5] = "GETCOLORTABLE";
    MetafileEscapes[MetafileEscapes["FLUSHOUT"] = 6] = "FLUSHOUT";
    MetafileEscapes[MetafileEscapes["DRAFTMODE"] = 7] = "DRAFTMODE";
    MetafileEscapes[MetafileEscapes["QUERYESCSUPPORT"] = 8] = "QUERYESCSUPPORT";
    MetafileEscapes[MetafileEscapes["SETABORTPROC"] = 9] = "SETABORTPROC";
    MetafileEscapes[MetafileEscapes["STARTDOC"] = 10] = "STARTDOC";
    MetafileEscapes[MetafileEscapes["ENDDOC"] = 11] = "ENDDOC";
    MetafileEscapes[MetafileEscapes["GETPHYSPAGESIZE"] = 12] = "GETPHYSPAGESIZE";
    MetafileEscapes[MetafileEscapes["GETPRINTINGOFFSET"] = 13] = "GETPRINTINGOFFSET";
    MetafileEscapes[MetafileEscapes["GETSCALINGFACTOR"] = 14] = "GETSCALINGFACTOR";
    MetafileEscapes[MetafileEscapes["META_ESCAPE_ENHANCED_METAFILE"] = 15] = "META_ESCAPE_ENHANCED_METAFILE";
    MetafileEscapes[MetafileEscapes["SETPENWIDTH"] = 16] = "SETPENWIDTH";
    MetafileEscapes[MetafileEscapes["SETCOPYCOUNT"] = 17] = "SETCOPYCOUNT";
    MetafileEscapes[MetafileEscapes["SETPAPERSOURCE"] = 18] = "SETPAPERSOURCE";
    MetafileEscapes[MetafileEscapes["PASSTHROUGH"] = 19] = "PASSTHROUGH";
    MetafileEscapes[MetafileEscapes["GETTECHNOLOGY"] = 20] = "GETTECHNOLOGY";
    MetafileEscapes[MetafileEscapes["SETLINECAP"] = 21] = "SETLINECAP";
    MetafileEscapes[MetafileEscapes["SETLINEJOIN"] = 22] = "SETLINEJOIN";
    MetafileEscapes[MetafileEscapes["SETMITERLIMIT"] = 23] = "SETMITERLIMIT";
    MetafileEscapes[MetafileEscapes["BANDINFO"] = 24] = "BANDINFO";
    MetafileEscapes[MetafileEscapes["DRAWPATTERNRECT"] = 25] = "DRAWPATTERNRECT";
    MetafileEscapes[MetafileEscapes["GETVECTORPENSIZE"] = 26] = "GETVECTORPENSIZE";
    MetafileEscapes[MetafileEscapes["GETVECTORBRUSHSIZE"] = 27] = "GETVECTORBRUSHSIZE";
    MetafileEscapes[MetafileEscapes["ENABLEDUPLEX"] = 28] = "ENABLEDUPLEX";
    MetafileEscapes[MetafileEscapes["GETSETPAPERBINS"] = 29] = "GETSETPAPERBINS";
    MetafileEscapes[MetafileEscapes["GETSETPRINTORIENT"] = 30] = "GETSETPRINTORIENT";
    MetafileEscapes[MetafileEscapes["ENUMPAPERBINS"] = 31] = "ENUMPAPERBINS";
    MetafileEscapes[MetafileEscapes["SETDIBSCALING"] = 32] = "SETDIBSCALING";
    MetafileEscapes[MetafileEscapes["EPSPRINTING"] = 33] = "EPSPRINTING";
    MetafileEscapes[MetafileEscapes["ENUMPAPERMETRICS"] = 34] = "ENUMPAPERMETRICS";
    MetafileEscapes[MetafileEscapes["GETSETPAPERMETRICS"] = 35] = "GETSETPAPERMETRICS";
    MetafileEscapes[MetafileEscapes["POSTSCRIPT_DATA"] = 37] = "POSTSCRIPT_DATA";
    MetafileEscapes[MetafileEscapes["POSTSCRIPT_IGNORE"] = 38] = "POSTSCRIPT_IGNORE";
    MetafileEscapes[MetafileEscapes["GETDEVICEUNITS"] = 42] = "GETDEVICEUNITS";
    MetafileEscapes[MetafileEscapes["GETEXTENDEDTEXTMETRICS"] = 256] = "GETEXTENDEDTEXTMETRICS";
    MetafileEscapes[MetafileEscapes["GETPAIRKERNTABLE"] = 258] = "GETPAIRKERNTABLE";
    MetafileEscapes[MetafileEscapes["EXTTEXTOUT"] = 512] = "EXTTEXTOUT";
    MetafileEscapes[MetafileEscapes["GETFACENAME"] = 513] = "GETFACENAME";
    MetafileEscapes[MetafileEscapes["DOWNLOADFACE"] = 514] = "DOWNLOADFACE";
    MetafileEscapes[MetafileEscapes["METAFILE_DRIVER"] = 2049] = "METAFILE_DRIVER";
    MetafileEscapes[MetafileEscapes["QUERYDIBSUPPORT"] = 3073] = "QUERYDIBSUPPORT";
    MetafileEscapes[MetafileEscapes["BEGIN_PATH"] = 4096] = "BEGIN_PATH";
    MetafileEscapes[MetafileEscapes["CLIP_TO_PATH"] = 4097] = "CLIP_TO_PATH";
    MetafileEscapes[MetafileEscapes["END_PATH"] = 4098] = "END_PATH";
    MetafileEscapes[MetafileEscapes["OPENCHANNEL"] = 4110] = "OPENCHANNEL";
    MetafileEscapes[MetafileEscapes["DOWNLOADHEADER"] = 4111] = "DOWNLOADHEADER";
    MetafileEscapes[MetafileEscapes["CLOSECHANNEL"] = 4112] = "CLOSECHANNEL";
    MetafileEscapes[MetafileEscapes["POSTSCRIPT_PASSTHROUGH"] = 4115] = "POSTSCRIPT_PASSTHROUGH";
    MetafileEscapes[MetafileEscapes["ENCAPSULATED_POSTSCRIPT"] = 4116] = "ENCAPSULATED_POSTSCRIPT";
    MetafileEscapes[MetafileEscapes["POSTSCRIPT_IDENTIFY"] = 4117] = "POSTSCRIPT_IDENTIFY";
    MetafileEscapes[MetafileEscapes["POSTSCRIPT_INJECTION"] = 4118] = "POSTSCRIPT_INJECTION";
    MetafileEscapes[MetafileEscapes["CHECKJPEGFORMAT"] = 4119] = "CHECKJPEGFORMAT";
    MetafileEscapes[MetafileEscapes["CHECKPNGFORMAT"] = 4120] = "CHECKPNGFORMAT";
    MetafileEscapes[MetafileEscapes["GET_PS_FEATURESETTING"] = 4121] = "GET_PS_FEATURESETTING";
    MetafileEscapes[MetafileEscapes["MXDC_ESCAPE"] = 4122] = "MXDC_ESCAPE";
    MetafileEscapes[MetafileEscapes["SPCLPASSTHROUGH2"] = 4568] = "SPCLPASSTHROUGH2";
})(MetafileEscapes = exports.MetafileEscapes || (exports.MetafileEscapes = {}));
;
var PenStyle;
(function (PenStyle) {
    PenStyle[PenStyle["PS_COSMETIC"] = 0] = "PS_COSMETIC";
    PenStyle[PenStyle["PS_ENDCAP_ROUND"] = 0] = "PS_ENDCAP_ROUND";
    PenStyle[PenStyle["PS_JOIN_ROUND"] = 0] = "PS_JOIN_ROUND";
    PenStyle[PenStyle["PS_SOLID"] = 0] = "PS_SOLID";
    PenStyle[PenStyle["PS_DASH"] = 1] = "PS_DASH";
    PenStyle[PenStyle["PS_DOT"] = 2] = "PS_DOT";
    PenStyle[PenStyle["PS_DASHDOT"] = 3] = "PS_DASHDOT";
    PenStyle[PenStyle["PS_DASHDOTDOT"] = 4] = "PS_DASHDOTDOT";
    PenStyle[PenStyle["PS_NULL"] = 5] = "PS_NULL";
    PenStyle[PenStyle["PS_INSIDEFRAME"] = 6] = "PS_INSIDEFRAME";
    PenStyle[PenStyle["PS_USERSTYLE"] = 7] = "PS_USERSTYLE";
    PenStyle[PenStyle["PS_ALTERNATE"] = 8] = "PS_ALTERNATE";
    PenStyle[PenStyle["PS_ENDCAP_SQUARE"] = 256] = "PS_ENDCAP_SQUARE";
    PenStyle[PenStyle["PS_ENDCAP_FLAT"] = 512] = "PS_ENDCAP_FLAT";
    PenStyle[PenStyle["PS_JOIN_BEVEL"] = 4096] = "PS_JOIN_BEVEL";
    PenStyle[PenStyle["PS_JOIN_MITER"] = 8192] = "PS_JOIN_MITER";
})(PenStyle = exports.PenStyle || (exports.PenStyle = {}));
;
var BrushStyle;
(function (BrushStyle) {
    BrushStyle[BrushStyle["BS_SOLID"] = 0] = "BS_SOLID";
    BrushStyle[BrushStyle["BS_NULL"] = 1] = "BS_NULL";
    BrushStyle[BrushStyle["BS_HATCHED"] = 2] = "BS_HATCHED";
    BrushStyle[BrushStyle["BS_PATTERN"] = 3] = "BS_PATTERN";
    BrushStyle[BrushStyle["BS_INDEXED"] = 4] = "BS_INDEXED";
    BrushStyle[BrushStyle["BS_DIBPATTERN"] = 5] = "BS_DIBPATTERN";
    BrushStyle[BrushStyle["BS_DIBPATTERNPT"] = 6] = "BS_DIBPATTERNPT";
    BrushStyle[BrushStyle["BS_PATTERN8X8"] = 7] = "BS_PATTERN8X8";
    BrushStyle[BrushStyle["BS_DIBPATTERN8X8"] = 8] = "BS_DIBPATTERN8X8";
    BrushStyle[BrushStyle["BS_MONOPATTERN"] = 9] = "BS_MONOPATTERN";
})(BrushStyle = exports.BrushStyle || (exports.BrushStyle = {}));
;
var HatchStyle;
(function (HatchStyle) {
    HatchStyle[HatchStyle["HS_HORIZONTAL"] = 0] = "HS_HORIZONTAL";
    HatchStyle[HatchStyle["HS_VERTICAL"] = 1] = "HS_VERTICAL";
    HatchStyle[HatchStyle["HS_FDIAGONAL"] = 2] = "HS_FDIAGONAL";
    HatchStyle[HatchStyle["HS_BDIAGONAL"] = 3] = "HS_BDIAGONAL";
    HatchStyle[HatchStyle["HS_CROSS"] = 4] = "HS_CROSS";
    HatchStyle[HatchStyle["HS_DIAGCROSS"] = 5] = "HS_DIAGCROSS";
})(HatchStyle = exports.HatchStyle || (exports.HatchStyle = {}));
;
var TextAlign;
(function (TextAlign) {
    TextAlign[TextAlign["TA_NOUPDATECP"] = 0] = "TA_NOUPDATECP";
    TextAlign[TextAlign["TA_LEFT"] = 0] = "TA_LEFT";
    TextAlign[TextAlign["TA_TOP"] = 0] = "TA_TOP";
    TextAlign[TextAlign["TA_UPDATECP"] = 1] = "TA_UPDATECP";
    TextAlign[TextAlign["TA_RIGHT"] = 2] = "TA_RIGHT";
    TextAlign[TextAlign["TA_CENTER"] = 6] = "TA_CENTER";
    TextAlign[TextAlign["TA_BOTTOM"] = 8] = "TA_BOTTOM";
    TextAlign[TextAlign["TA_BASELINE"] = 24] = "TA_BASELINE";
    TextAlign[TextAlign["TA_RTLREADING"] = 256] = "TA_RTLREADING";
})(TextAlign = exports.TextAlign || (exports.TextAlign = {}));
;
var FloodFill;
(function (FloodFill) {
    FloodFill[FloodFill["FLOODFILLBORDER"] = 0] = "FLOODFILLBORDER";
    FloodFill[FloodFill["FLOODFILLSURFACE"] = 1] = "FLOODFILLSURFACE";
})(FloodFill = exports.FloodFill || (exports.FloodFill = {}));
