import { META_CREATEBRUSHINDIRECT } from "./META_CREATEBRUSHINDIRECT";
import { META_CREATEPENINDIRECT } from "./META_CREATEPENINDIRECT";
import { META_DELETEOBJECT } from "./META_DELETEOBJECT";
import { META_EOF } from "./META_EOF";
import { META_ESCAPE } from "./META_ESCAPE";
import { META_HEADER } from "./META_HEADER";
import { META_PLACEABLE } from "./META_PLACEABLE";
import { META_POLYGON } from "./META_POLYGON";
import { META_SELECTOBJECT } from "./META_SELECTOBJECT";
import { META_SETBKMODE } from "./META_SETBKMODE";
import { META_SETMAPMODE } from "./META_SETMAPMODE";
import { META_SETPOLYFILLMODE } from "./META_SETPOLYFILLMODE";
import { META_SETROP2 } from "./META_SETROP2";
import { META_SETTEXTALIGN } from "./META_SETTEXTALIGN";
import { META_SETTEXTCOLOR } from "./META_SETTEXTCOLOR";
import { META_SETWINDOWEXT } from "./META_SETWINDOWEXT";
import { META_SETWINDOWORG } from "./META_SETWINDOWORG";

export const RECORDS = {
    META_CREATEBRUSHINDIRECT,
    META_CREATEPENINDIRECT,
    META_DELETEOBJECT,
    META_EOF,
    META_ESCAPE,
    META_HEADER,
    META_PLACEABLE,
    META_POLYGON,
    META_SELECTOBJECT,
    META_SETBKMODE,
    META_SETMAPMODE,
    META_SETPOLYFILLMODE,
    META_SETROP2,
    META_SETTEXTALIGN,
    META_SETTEXTCOLOR,
    META_SETWINDOWEXT,
    META_SETWINDOWORG,
};
